pipeline:
  name: pod_popper
  identifier: pod_popper
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: pop
        identifier: pop
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev_cluster
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: approval
                  identifier: approval
                  spec:
                    approvalMessage: "Approve to DELETE the following resource:Service: <+service.name>Env: <+env.name>Cluster: <+infra.connector.name>"
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                        - account.security_team
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                    callbackId: <+infra.connector.name>
                  timeout: 1d
              - step:
                  type: K8sDelete
                  name: delete_deployment
                  identifier: delete_deployment
                  spec:
                    deleteResources:
                      type: ResourceName
                      spec:
                        resourceNames:
                          - deploy/<+service.name>-deployment
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  description: "Delete a k8s Deployment with a given Harness Service and Environment input. "
